# Generated by Django 4.2.3 on 2023-07-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcuser',
            name='username',
            field=models.CharField(max_length=64, verbose_name='사용자명'),
        ),
    ]
